### ISSUE TITLE
Browser triggers download

### ISSUE THREAD

**Issue by infabo** [lochmueller/staticfilecache#227]
## Bug Report

**Current Behavior**
If the **root-page** is of doktype `4` (shortcut) the browser triggers a download (apparently a gziped file).
This behaviour is only observable when staticfilecache enabled.

![image](https://user-images.githubusercontent.com/3999104/69372513-200a4280-0ca2-11ea-8577-2cc54c748f88.png)

![image](https://user-images.githubusercontent.com/3999104/69372491-17197100-0ca2-11ea-906c-cdb26e3b6d56.png)

**Expected behavior/output**
text/html document

**Environment**
- TYPO3 version(s): 9.5.11
- staticfilecache version: 10.0.1
- Is your TYPO3 installation set up with Composer (Composer Mode): yes
- OS: Linux

**Possible Solution**

**Additional context**

files in typo3temp/tx_staticfilecache folder

```
-rw-rw---- 1 inf inf  229 21. Nov 13:26 .htaccess
-rw-r--r-- 1 inf inf  384 21. Nov 13:26 index.config.json
-rw-r--r-- 1 inf inf   20 21. Nov 13:26 index.gz
```

.htaccess

```
<IfModule mod_expires.c>
	ExpiresActive on
	ExpiresByType text/html M86400
</IfModule>




	<ifModule mod_headers.c>
		
				Header set X-SFC-Tags "sfc_pageId_8472, sfc_domain_website_ddev_site"
		
	</ifModule>
```

index.config.json

```
{
    "generated": "Thu, 21 Nov 2019 13:26:56 +0100",
    "headers": {
        "location": [
            "https:\/\/website.ddev.site\/blutspende-einrichtungen-1"
        ],
        "X-SFC-Cachable": [
            "1"
        ],
        "X-SFC-Tags": [
            "sfc_pageId_8472",
            "sfc_domain_website_ddev_site"
        ]
    }
}
```

**Comment by MartinH0** [comment]
1. pls update to the newest Version of SFC
2. Pls keep in mind adjusting the htaccess as it changes between v9 and v10.
3. See here https://github.com/lochmueller/staticfilecache/issues/225#issuecomment-557472791 and apply this additional changes to make SFC handle compressed files properly

Alternatively you can disable compression.

**Comment by infabo** [comment]
The problem is **only** (i thought I made that fact **BOLD**) on a **shortcut** **rootpage**. **everywhere** **else** it is working **fine**. this particular TYPO3 instance has 26 rootpages (non-shortcuts and this one as shortcut). all in total ~30k pages. and this is the only one site which isnt working.

so yeah, i adjusted my htaccess especially for v10.

I'll disable compression and see what it will do then.

**Comment by infabo** [comment]
sry, pinned to 10.0.1 cause 10.0.2 broke my instance last time. i'll update and report back again.

**Comment by infabo** [comment]
I am pretty sure the issue was already described at #216 and was fixed with this commit https://github.com/lochmueller/staticfilecache/commit/54dd5d71d2295b1f847c11108f25c5821ef879dc

**Comment by infabo** [comment]
Still triggering the download with 10.1.1. going to investigate further.

**Comment by infabo** [comment]
Ok, 10.1.1 and still the same download.gz file.

Checked the .htaccess rules. they are most current ones.

I don't understand how these additional rules for ".gzip" file extensions should help.

https://github.com/lochmueller/staticfilecache/issues/225#issuecomment-557472791

As you can see in my original post, there is only a "index.gz" file. ".gz". Not ".gzip". So I don't get the point.

**Comment by MartinH0** [comment]
> As you can see in my original post, there is only a "index.gz" file. ".gz". Not ".gzip". So I don't get the point.

Yes SFC creates .gz files of the index.html . You never told what file was downloaded.
I had a similar issue where the same happened to css and js assets which was caused by not setting the right Mimetype and Encoding in the htaccess.

Your Issue seems to be related to getting the `index.gz` downloaded when calling the site.
- Thats wasnt clear for me.

Actually I'm running on SFC 10.1.0 and do not encounter this issue nor can I reproduce it.

Anyway I think it would be usefull to see the config of your SFC Setup (in your LocalConfiguration.php)

Should look like this:

```
'EXTENSIONS' => [
    'staticfilecache' => [
        ###Your Config###
    ],
],
```

Did you encounter this Problem in earlier versions of SFC?

**Comment by MartinH0** [comment]
> **Additional context**
> 
> files in typo3temp/tx_staticfilecache folder
> 
> ```
> -rw-rw---- 1 inf inf  229 21. Nov 13:26 .htaccess
> -rw-r--r-- 1 inf inf  384 21. Nov 13:26 index.config.json
> -rw-r--r-- 1 inf inf   20 21. Nov 13:26 index.gz
> ```

Also strange, for every `index.gz` file I do have a normal version (not GZIPed) of the index which just gets called `index`.
But as this just happens to shortcuts it is maybe not related to this.

**Comment by MartinH0** [comment]
> 	<ifModule mod_headers.c>
> 		
> 				Header set X-SFC-Tags "sfc_pageId_8472, sfc_domain_website_ddev_site"
> 		
> 	</ifModule>

Where is your `Header set Content-Type`?
Pls navigate in TYPO3 to Settings, edit the setting of SFC.
Edit the field `Valid .htaccess headers`
Now Change from whatever it is to `Content-Type,Content-Language,Link,X-SFC-Tags`
Somehow "Content-Type" seems to be missing there, but explanation states

> "Content-Type" is recommended.

**Comment by infabo** [comment]
For v10 I wiped my staticfilecache config to get the new defaults. I did just change the one or other setting (like disable staticfilecache for development).

![image](https://user-images.githubusercontent.com/3999104/69484392-0ba97f80-0e33-11ea-9346-0ac05106d110.png)

I did not change that. So when these headers should be always there, then this is a bug too.

**Comment by infabo** [comment]
Okay, now it seems to work like expected. there is no cache-folder generated for the shortcut-rootpage -> only for the target page. the headers in .htaccess are there and I dont get a download.gz file anymore. very strange. seems like I missed maybe to clear the tx_staticfilecache folder after the upgrade to 10.1.1. Guess I can close.

**Comment by infabo** [comment]
> Anyway I think it would be usefull to see the config of your SFC Setup (in your LocalConfiguration.php)
> 
> Should look like this:
> 
> ```
> 'EXTENSIONS' => [
>     'staticfilecache' => [
>         ###Your Config###
>     ],
> ],
> ```

Just for reference my config:

```
  staticfilecache:
        backendDisplayMode: both
        boostMode: '0'
        cacheTagsEnable: '0'
        clearCacheForAllDomains: '1'
        debugHeaders: '0'
        disableInDevelopment: '0'
        enableGeneratorBrotli: '0'
        enableGeneratorGzip: '1'
        enableGeneratorManifest: '0'
        enableGeneratorPlain: '0'
        hashUriInCache: '0'
        htaccessTemplateName: 'EXT:staticfilecache/Resources/Private/Templates/Htaccess.html'
        overrideCacheDirectory: ''
        rawurldecodeCacheFileName: '0'
        renameTablesToOtherPrefix: '0'
        sendCacheControlHeader: '1'
        sendCacheControlHeaderRedirectAfterCacheTimeout: '0'
        sendHttp2PushEnable: '1'
        sendHttp2PushFileExtensions: 'css,js'
        sendHttp2PushFileLimit: '10'
        useFallbackMiddleware: '1'
        useReverseUriLengthInPriority: '1'
        validHtaccessHeaders: 'Content-Type,Content-Language,Link,X-SFC-Tags'
```

> Maybe this question is dumb, but do you use Apache only or behind nginX, if behind nginX, which WebServer does beliver the index.gz file?

Yep, there is a proxy (I guess it is a HTTPS offloader) as the hoster somewhen mentioned when we requested HTTP/2. But I guess this did not cause the issue here, since it is working now.

In the past I experiences gzip-encoded output in browsers quite often - and randomly. the behaviour was not consistent. it was like Apache did content-type roulette. But a download.gz file was new ;)
