### ISSUE TITLE
Scheduler task to flush cache is missing

### ISSUE THREAD

**Issue by seirerman** [lochmueller/staticfilecache#365]
## Bug Report

**Current Behavior**
After upgrading from 11.1.7 to 12.4.5 I noticed that the task to flush the caches was gone. Previously created tasks just said "Befehl mit Bezeichner staticfilecache:flushCache ist nicht registriert worden"

**Environment**
- TYPO3 version(s): 10.4.31
- staticfilecache version: 12.4.5
- Is your TYPO3 installation set up with Composer (Composer Mode): yes

**Possible Solution**
The task isn't registered because its entry is missing in Configuration/Services.yaml:

```
  SFC\Staticfilecache\Command\FlushCacheCommand:
    tags:
      - name: 'console.command'
        description: 'Flush the cache. If the boost mode is active, all pages are added to the queue (you have to run the BoostQueueRun Command to recrawl the pages). If you use the force-boost-mode-flush argument, you directly drop the cache even the page is in Boostmode.'
        command: 'staticfilecache:flushCache'
```

**Additional context**
Simply adding the code and flushing all caches didn't bring back the scheduler task. Only uninstalling and the installing the extension in the extension manager helped. Not sure why, but worth mentioning...
